### ISSUE TITLE
Analyzing EC2 data issue...

### ISSUE THREAD

**Issue by leo100** [iSECPartners/Scout2#32]
I'm using dev branch.

I'm running Scout against one of the environments:
$ python Scout2.py --env company-services --csv-credentials /tmp/sys-monitoring-credentials-company-services.csv

And getting this:

Fetching IAM credential report...
Analyzing EC2 data...
Traceback (most recent call last):
  File "Scout2.py", line 197, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 124, in main
    method(aws_config['services'][service], aws_config['account_id'], args.force_write)
  File "/home/myuser/scout_dev/dev-listall/AWSScout2/utils_ec2.py", line 21, in analyze_ec2_config
    link_elastic_ips(ec2_info)
  File "/home/myuser/scout_dev/dev-listall/AWSScout2/utils_ec2.py", line 78, in link_elastic_ips
    go_to_and_do(ec2_config, None, ['regions', 'elastic_ips'], None, link_elastic_ips_callback1, {})
  File "/home/myuser/scout_dev/dev-listall/AWSScout2/utils.py", line 140, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/home/myuser/scout_dev/dev-listall/AWSScout2/utils.py", line 132, in go_to_and_do
    callback(aws_config, current_config[key][value], path, current_path, value, callback_args)
  File "/home/myuser/scout_dev/dev-listall/AWSScout2/utils_ec2.py", line 84, in link_elastic_ips_callback1
    go_to_and_do(ec2_config, None, ['regions', 'vpcs', 'instances'], None, link_elastic_ips_callback2, {'instance_id': instance_id, 'elastic_ip': elastic_ip})
  File "/home/myuser/scout_dev/dev-listall/AWSScout2/utils.py", line 140, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/home/myuser/scout_dev/dev-listall/AWSScout2/utils.py", line 140, in go_to_and_do
    go_to_and_do(aws_config, current_config[key][value], copy.deepcopy(path), tmp, callback, callback_args)
  File "/home/myuser/scout_dev/dev-listall/AWSScout2/utils.py", line 132, in go_to_and_do
    callback(aws_config, current_config[key][value], path, current_path, value, callback_args)
  File "/home/myuser/scout_dev/dev-listall/AWSScout2/utils_ec2.py", line 91, in link_elastic_ips_callback2
    printInfo('Warning: public IP address exists (%s) for an instance associated with an elastic IP (%s)' % (ec2_info['regions'][r]['vpcs'][v]['instances'][i]['PublicIpAddress'], eip))
NameError: global name 'ec2_info' is not defined

Can you please look into this error?

**Comment by l01cd3v** [comment]
Which dev branch? All dev branches have been merged with master so you shouldn't need to work off of a dev branch.

Looking at the log, it seems that fetching the ec2 config failed (or didn't happened), which causes the analysis to fail. Can you please double check if that happens on master too?

**Comment by leo100** [comment]
I was using dev-listall but thanks for telling me that All dev branches merged with master.
I'll clone master now ;)
And yeah I can confirm that it's working again, might be a connectivity issue at the time.
Closing....

**Comment by l01cd3v** [comment]
Thanks. I'm looking into "deleting" these dev branches to make it less confusing...
